# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 499)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 370, 460))
        self.listView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.listView.setObjectName("listView")
        self.CprPB = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CprPB.setGeometry(QtCore.QRect(80, 50, 200, 50))
        self.CprPB.setObjectName("CprPB")
        self.StorePB = QtWidgets.QPushButton(parent=self.centralwidget)
        self.StorePB.setGeometry(QtCore.QRect(80, 170, 200, 50))
        self.StorePB.setObjectName("StorePB")
        self.CgPB = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CgPB.setGeometry(QtCore.QRect(80, 110, 200, 50))
        self.CgPB.setObjectName("CgPB")
        self.SalePB = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SalePB.setGeometry(QtCore.QRect(80, 230, 200, 50))
        self.SalePB.setObjectName("SalePB")
        self.ReportPB = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ReportPB.setGeometry(QtCore.QRect(80, 290, 200, 50))
        self.ReportPB.setObjectName("ReportPB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 369, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CprPB.setText(_translate("MainWindow", "ایجاد طرف های تولید"))
        self.StorePB.setText(_translate("MainWindow", "انبار"))
        self.CgPB.setText(_translate("MainWindow", "ایجاد کالا"))
        self.SalePB.setText(_translate("MainWindow", "فروش"))
        self.ReportPB.setText(_translate("MainWindow", "گزارش"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
